spring:
  application:
    name: service-registry
server:
  port: 8761

eureka:
  instance:
    hostname: serviceregistry
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
    max-threads-for-peer-replication: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
