# spring.application.name = auth-service
# server.port=8102
# eureka.client.service-url.default-zone = http://localhost:8761/eureka
# server.port=8102

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:/config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  main:
    allow-circular-references: true     

    #function:
     # defination: userCreatedOutput
   # stream:
      #kafka:
       # binder:
        #  brokers: 192.168.1.8
         # defaultBrokerPort: 9092
    #  bindings:
      #  userCreatedOutput-out-0:
      #    destination: userCreatedOutput
          #binder: kafka
          #group: group
          #consumer:
          #  concurrency: 10
          #  max-attempts: 3

  datasource:
    url: jdbc:mysql://localhost:3306/ecommercedb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: rahul1
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update     
    

eureka:
  client:
    service-url:
      default-zone: http://serviceregistry:8761/eureka/

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
